name: Build Rocky 8
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # check out source
      - uses: actions/checkout@v2
      # setup jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # compile apache http server
      - name: Compile Rocky
        uses: ./web-compile/action/rocky8
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      # packaging project
      - name: Build with Maven
        run: mvn -B package --file web-dist/pom.xml -Dcompile.os.name=rocky8
      # get project version
      - name: Bump Version
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pom-path: web-dist
      # upload install file to AWS S3
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'web-dist/target/lena-work'
          destination_dir: 'openlena/web'
      # setup Container Image Build module
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Setup repository access info
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # get repository name
      - id: repository
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      # build docker container image and push to repository
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=rockylinux/rockylinux:8.4
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_rocky8
